### 72. How to swap two rows of an array?

In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[4,5,6]])
print(f"Original array: {arr}")
tmp = np.copy(arr)
tmp[0] = arr[1]
tmp[1] = arr[0]
arr = tmp
print(f"Swapped array: {arr}")

Original array: [[1 2 3]
 [4 5 6]]
Swapped array: [[4 5 6]
 [1 2 3]]


### 75. How to compute averages using a sliding window over an array?

In [4]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
averages = np.cumsum(arr) / np.size(arr)
averages

array([0.1, 0.3, 0.6, 1. , 1.5, 2.1, 2.8, 3.6, 4.5, 5.5])